### ISSUE TITLE
Create mode where incorrect assignments trigger errors

### ISSUE THREAD

**Issue by Beliavsky** [ShinobuAmasaki/uint-fortran#1]
Would it be possible to create a version of uint such that

`a = -10`

results in the program terminating with `ERROR STOP`?

**Comment by ShinobuAmasaki** [comment]
I think it's probably possible and wouldn't be a bad idea to make one.

If you don't mind, could you give me an example of a situation where this ERROR STOP is particularly necessary?

**Comment by ShinobuAmasaki** [comment]
This feature added in the version 0.1. 

cf. [README.md#forbid-assignment-of-negative-numbers](https://github.com/ShinobuAmasaki/uint-fortran/blob/main/README.md#forbid-assignment-of-negative-numbers)
